### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by dluigi** [cuynu/ytvancedx#227]
Environment
===========
Platform: Android 13
YouTube Vanced Version: 17.33.42
Vanced MicroG: 0.2.28.233013
Device: Galaxy S21

Description
===========
There is no option to cast from mobile to Smart(Android) TV on version 17.33.42
I used to have 18.03.22 veraion which i found in the settings the option to turn on cast button in the player.. Now I can't find it.

**Comment by cuynu** [comment]
no support for rvx or inotia builds
