### ISSUE TITLE
[Bug] Video starts buffering around 1 minute

### ISSUE THREAD

**Issue by WOLF73748** [cuynu/ytvancedx#229]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform: Android

OS Version: 12

YouTube Vanced Version: YouTube.Vanced.v18.02.33_Black_Universal_hotfix.apk

Vanced MicroG: 0.2.27.231612

Device: Samsung S10+

Description
===========
Video starts buffering around 1 minute into the video. I have tried uninstalling both microg and youtube vanced. Then reinstalling both of microg and youtube vanced as well as signing back into my account.
Nothing is working properly. 

Steps to reproduce
==================
1. Launch app and watch a video 
2. 1 minute into the video, buffering starts happening.
3. I then uninstalled both microg and youtube vanced then reinstalled them back as well as sign back in.
4. Relaunch the app, then select the same video before.
5. Video starts buffering again.

Expected result
===============
Youtube vanced to work as per usual nothing gone wrong.

Actual result
=============
Videos on youtube vanced start buffering.

Screenshots / Videos / Logs
===========================

Unable to attach video

Notes
=====
The same thing happened back in may, but then reported the issue and it got fixed.

**Comment by txnvxr** [comment]
I have the same issue on version 18.21.34 (RVX) and since the revanced extended versions are discontinued reporting issues won't help, while I wait for a stable version of Vanced+ to be released I'm using revanced which doesn't have the buffering after 1 min. As for the test version of Vanced+ I can't even get it to open

**Comment by bhavukp** [comment]
I'm also facing the buffer issue on both RVX(18.31.24) and Vanced 17.33.42 after clean install with microG. I have to add one more thing even my original YouTube Google App is also having the same issue. Can someone confirm if their original app is also buffering the same ?

**Comment by WOLF73748** [comment]
> I'm also facing the buffer issue on both RVX(18.31.24) and Vanced 17.33.42 after clean install with microG. I have to add one more thing even my original YouTube Google App is also having the same issue. Can someone confirm if their original app is also buffering the same ?

Hi, do

**Comment by WOLF73748** [comment]
> I'm also facing the buffer issue on both RVX(18.31.24) and Vanced 17.33.42 after clean install with microG. I have to add one more thing even my original YouTube Google App is also having the same issue. Can someone confirm if their original app is also buffering the same ?

Yeah, i think all the apk for youtube vanced are experiencing the same or similar problems. Not so sure about the original youtube app.

**Comment by WOLF73748** [comment]
> I have the same issue on version 18.21.34 (RVX) and since the revanced extended versions are discontinued reporting issues won't help and it's unlikely it will ever be fixed, while I wait for a stable version of Vanced+ to be released I'm using revanced which doesn't have the buffering after 1 min. As for the test version of Vanced+ I can't even get it to open

Ok, i will wait till vanced+ to come out. I did try to use it earlier seems to have the same problem as you of not being able to launch. Also, which site is revanced. 

Thanks for the information as well

**Comment by txnvxr** [comment]
This is the official Revanced website https://revanced.app/
And this is the GitHub link https://github.com/ReVanced
When you go on the website you will need to download the revanced manager
You will also need the official YouTube app but version 18.23.35, you need the APK version which u can get from APK mirror link - https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-23-35-release/youtube-18-23-35-2-android-apk-download/
You also need to uninstall any updates to the official YouTube app before installing the slightly older version. After that's done and you successfully installed  YouTube v18.23.35 open the revanced manager, then go to settings and enable both of the toggles for experimental features, after that go to patcher and select the YouTube app select the patches that u want if u want don't want the black theme uncheck "custom theme" for the standard dark theme. After successful install of revanced make sure that in revanced settings > misc  Spoof app signature is turned on. This will fix the buffering issue

**Comment by txnvxr** [comment]
> > I have the same issue on version 18.21.34 (RVX) and since the revanced extended versions are discontinued reporting issues won't help and it's unlikely it will ever be fixed, while I wait for a stable version of Vanced+ to be released I'm using revanced which doesn't have the buffering after 1 min. As for the test version of Vanced+ I can't even get it to open
> 
> Ok, i will wait till vanced+ to come out. I did try to use it earlier seems to have the same problem as you of not being able to launch. Also, which site is revanced.
> 
> Thanks for the information as well

This is the official Revanced website https://revanced.app/
And this is the GitHub link https://github.com/ReVanced
When you go on the website you will need to download the revanced manager
You will also need the official YouTube app but version 18.23.35, you need the APK version which u can get from APK mirror link - https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-23-35-release/youtube-18-23-35-2-android-apk-download/
You also need to uninstall any updates to the official YouTube app before installing the slightly older version. After that's done and you successfully installed  YouTube v18.23.35 open the revanced manager, then go to settings and enable both of the toggles for experimental features, after that go to patcher and select the YouTube app select the patches that u want if u want don't want the black theme uncheck "custom theme" for the standard dark theme. After successful install of revanced make sure that in revanced settings > misc  Spoof app signature is turned on. This will fix the buffering issue

**Comment by WOLF73748** [comment]
> > > I have the same issue on version 18.21.34 (RVX) and since the revanced extended versions are discontinued reporting issues won't help and it's unlikely it will ever be fixed, while I wait for a stable version of Vanced+ to be released I'm using revanced which doesn't have the buffering after 1 min. As for the test version of Vanced+ I can't even get it to open
> > 
> > 
> > Ok, i will wait till vanced+ to come out. I did try to use it earlier seems to have the same problem as you of not being able to launch. Also, which site is revanced.
> > Thanks for the information as well
> 
> This is the official Revanced website https://revanced.app/ And this is the GitHub link https://github.com/ReVanced When you go on the website you will need to download the revanced manager You will also need the official YouTube app but version 18.23.35, you need the APK version which u can get from APK mirror link - https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-23-35-release/youtube-18-23-35-2-android-apk-download/ You also need to uninstall any updates to the official YouTube app before installing the slightly older version. After that's done and you successfully installed YouTube v18.23.35 open the revanced manager, then go to settings and enable both of the toggles for experimental features, after that go to patcher and select the YouTube app select the patches that u want if u want don't want the black theme uncheck "custom theme" for the standard dark theme. After successful install of revanced make sure that in revanced settings > misc Spoof app signature is turned on. This will fix the buffering issue

Ok, thanks for info, you have been very helpful.
