### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by elhaddajiOtmane** [cuynu/ytvancedx#230]
Environment
===========
Platform:Android 
OS Version:13
YouTube Vanced Version:18.21.34
Vanced MicroG:4.64.51
Device:A71

Description
===========
All videos stopped after 1 minute 
Or not working after 1min

Actual result
=============

Screenshots / Videos / Logs
===========================

**Comment by ibeXedi** [comment]
Same here on android 12.
But even official YouTube App isnt working. What about yours?

**Comment by cuynu** [comment]
dont report issue related to rvx builds, are you read warning?

**Comment by cuynu** [comment]
i know you maybe a developer, but i still need close this issue as it affect my development progress for Vanced+ that completely rewritten from scratch with java and kotlin
