### ISSUE TITLE
[Bug] YouTube Vanced+ not working 

### ISSUE THREAD

**Issue by FaboThePlayer** [cuynu/ytvancedx#231]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version: 13
YouTube Vanced Version: -
Vanced MicroG: 0.2.27.231413
Device: POCO F3

Description
===========
I'm trying every version of Vanced possible cause I have buffering problem, and heard that it is fixed in 18.25>. Enabled protobuf but it's still buffering, only on my main account.

Steps to reproduce
==================
1. Install YT Vanced+
2. Start the app

Expected result
===============
App loads correctly and shows main site.

Actual result
=============
App does not load at all.

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by ibeXedi** [comment]
For me it seems like a Google/YouTube issue.
Im on the latest microG version and Vanced version and with or without buffer fix it stops working after some time.
The funny thing is that even with the official YouTube App the same thing happens.
Maybe we just need to wait until YouTube fixes there stuff.

**Comment by cuynu** [comment]
Vanced+ does not open at all. you are using deprecated version

**Comment by FaboThePlayer** [comment]
I downloaded latest version possible. You mean I'm using deprecated version of microG?
