### ISSUE TITLE
Unable to download songs in yt Music[Bug] 

### ISSUE THREAD

**Issue by rahulsingh-03** [cuynu/ytvancedx#232]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version:13
YouTube Music Vanced Version:5.16.51
Vanced MicroG:0.2.24.220220
Device:poco m4 pro 5g

Description
===========
Unable to download song in ytmusic vanced

Steps to reproduce
==================
1.open yt music vanced
2.play any song
3.click download button 
Or 
1. Open yt music vanced
2. Head to any playlist
3. Then click download to download whole playlist 

Expected result
===============
Song start downloading and play in offline mode.

Actual result
=============
Nothing happens when click in download button 

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
dont report issue related to rvx builds

**Comment by cuynu** [comment]
dont report issue related to rvx builds

**Comment by rahulsingh-03** [comment]
> dont report issue related to rvx builds

What is rvx build could you please explain it.
