### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LJGJM** [cuynu/ytvancedx#233]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android 11
OS Version: Android 11 OneUI 4
YouTube Vanced Version: 18.28.33
Vanced MicroG: latest
Device: m22 samsung

Description
===========

Steps to reproduce
==================
1. start app

Expected result
===============
actually loads

Actual result
=============
crash

Screenshots / Videos / Logs
===========================
do i really need this? it just doesnt open

Notes
=====

**Comment by cuynu** [comment]
known issue, wait for stable release
