### ISSUE TITLE
App won't even start

### ISSUE THREAD

**Issue by Skyw3lker** [cuynu/ytvancedx#234]
Environment
===========
Platform: Android
OS Version:  12
YouTube Vanced Version: 18.28.33 DEVELOPMENT TESTING
Vanced MicroG:  v0.2.28.233013
Device: Realme 7

Description
===========

Steps to reproduce
==================
1. Download the APK, install it
2. Nothing, the app won't open
I tried restart, delete the cash and data, uninstall and install and with the same result.

**Comment by NamNam0w0** [comment]
I thought I was the only one

**Comment by iBeelicious** [comment]
Sabe here /:

**Comment by romelle89** [comment]
The app only load untill 1:10 we have a problem i use 18.21.34

**Comment by Skyw3lker** [comment]
> The app only load untill 1:10 we have a problem i use 18.21.34

This version used to work perfectly, now it stops after a few seconds, buffering and loading forever... that's why i needed an upgrade

**Comment by hanwuli** [comment]
> > The app only load untill 1:10 we have a problem i use 18.21.34
> 
> This version used to work perfectly, now it stops after a few seconds, buffering and loading forever... that's why i needed an upgrade
It often stops playing and buffering after several minutes these days.

**Comment by sant3e** [comment]
Not working here as well. Z Fold 3, it crashes on open

**Comment by cuynu** [comment]
known issue, wait for Vanced+ usable release
