### ISSUE TITLE
[Bug] buffering even tho ive set buffering on all to 1

### ISSUE THREAD

**Issue by Sekiro21** [cuynu/ytvancedx#235]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version: 13
YouTube Vanced Version:17.33.42
Vanced MicroG:0.2.26.225014
Device: s23 ultra 5g

Description
===========
So my videos that are long work for like forst 30 seconds and then the video stops and starts to buffer for a very long time and the video doesnt play anymore, ive chnaged the buffering settings from the default one to 1 all of them and it still doesnt work

Steps to reproduce
==================
1. Just get in app
2. Click any video longer than 1min 
3. After 30 settings video stops 
4.

Expected result
===============
Videos wont work at all

Actual result
=============
Videos dont work

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
Try v18.21.34
