### ISSUE TITLE
can't refresh homepage [Bug] 

### ISSUE THREAD

**Issue by EgorPolitov** [cuynu/ytvancedx#237]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION.

Environment
===========
Platform:Android
OS Version: 13
YouTube Vanced Version: 18.21.34
Vanced MicroG: latest
Device: Tecno camon 20 pro 5g

Description
===========
after the first re-entry into the application, it is impossible to update the main page (when reinstalling, the exact same problem, some older versions do not have this problem)

Steps to reproduce
==================
1. Open app
2. Close app
3. Update the main page

Expected result
===============
it will be possible to refresh the main page

Actual result
=============
can't refresh homepage

Screenshots / Videos / Logs
===========================
https://youtube.com/shorts/m41Y4Z_Mi_s?feature=share

Notes
=====

**Comment by cuynu** [comment]
No fix for RVX related build. pls read the warning before create issue.
