### ISSUE TITLE
Buffer Issue, Protobuf Doesnt Help

### ISSUE THREAD

**Issue by RoyWallach** [cuynu/ytvancedx#238]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION. ALSO DO NOT REPORT ISSUE FROM ANY BUILD OLDER THAN 18.28.33 or v6.xx.xx+.

Environment
===========
Platform:Android
OS Version:
YouTube Vanced Version: 18.02.33
Vanced MicroG: 0.2.28.233013
Device:

Description
===========
Buffer Issue 

Steps to reproduce
==================
1. start a video 
2. wait about a minute
3.
4.

Expected result
===============
video continues 

Actual result
=============
video stuck on buffering

Screenshots / Videos / Logs
===========================

Notes
=====
recommended protobuf spoof solution, doesn't work

**Comment by cuynu** [comment]
https://github.com/cuynu/archive/releases/download/18.21.34/YouTube.Vanced.v18.21.34_Black_Universal_bye.apk

**Comment by cuynu** [comment]
ALSO DO NOT REPORT ISSUE FROM ANY BUILD OLDER THAN 18.28.33 or v6.xx.xx+.
