### ISSUE TITLE
[Bug] yt music vanced keeps crashing when I open ot

### ISSUE THREAD

**Issue by taylod44** [cuynu/ytvancedx#239]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION. ALSO DO NOT REPORT ISSUE FROM ANY BUILD OLDER THAN 18.28.33 or v6.xx.xx+.

Environment
===========
Platform:Android
OS Version:12
YouTube Vanced Version: music 5.16.51
Vanced MicroG:0.2.28.233013
Device:moto g power 2022

Description
===========
The YouTube vanced keep crashing as soon as I open it

Steps to reproduce
==================
1.open app
2.load for a second
3.crashes
4.

Expected result
===============
App opens

Actual result
=============
App crashes

Screenshots / Videos / Logs
===========================

Notes
=====
I did just update to the newest one because the last version stop recognizing my accounts and I'm unsure why

**Comment by cuynu** [comment]
https://github.com/cuynu/archive/releases/tag/5.39.52
