### ISSUE TITLE
[Bug]  YouTube music can't open 

### ISSUE THREAD

**Issue by emma51053** [cuynu/ytvancedx#241]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION. ALSO DO NOT REPORT ISSUE FROM ANY BUILD OLDER THAN 18.28.33 or v6.xx.xx+.

Environment
===========
Platform:Android
OS Version:13
YouTube Vanced Version:YouTube Music Vanced 5.16.51
Vanced MicroG: 0.2.28.233013
Device: Google pixel 6 pro

Description
===========

Steps to reproduce
==================
1.open app
2.load for a second
3.crashes
4.

Thanks 

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
===========================

Notes
=====

**Comment by cuynu** [comment]
https://github.com/cuynu/archive/releases/tag/5.39.52
