### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Koknsil** [cuynu/ytvancedx#242]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION. ALSO DO NOT REPORT ISSUE FROM ANY BUILD OLDER THAN 18.28.33 or v6.xx.xx+.

Environment
===========
Platform:Android
OS Version:12
YouTube Vanced Version:17.33.42
Vanced MicroG: 0.2.28.233013
Device:

Description
===========

Steps to reproduce
=================
1.unable to play videos using Wifi
2.please give Key on YtVenced
3.
4.

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
===========================
![Screenshot_2023-09-07-17-58-38-178_com vanced android youtube](https://github.com/cuynu/ytvancedx/assets/144338113/6657b918-559a-42f6-91e3-4faf02e0ee71)

Notes
=====

**Comment by cuynu** [comment]
try v18.21.34
