### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by quackhub4343** [cuynu/ytvancedx#244]
PLEASE FILL OUT THIS FORM, DO NOT CREATE ISSUE WITHOUT THIS FORM, OTHERWISE, ISSUE WILL CLOSE WITHOUT ANY NOTICE OR CONVERT TO DISCUSSION. ALSO DO NOT REPORT ISSUE FROM ANY BUILD OLDER THAN 18.28.33 or v6.xx.xx+.

Environment
===========
Platform:Android
OS Version:
YouTube Vanced Version:
Vanced MicroG:
Device:

Description
===========

Steps to reproduce
==================
1.
2.
3.
4.

Expected result
===============

Actual result
=============

Screenshots / Videos / Logs
===========================
![IMG_20230926_092751](https://github.com/cuynu/ytvancedx/assets/146051885/19553a46-d810-4cae-abed-f4b7774490f6)

Notes
=====
Can you please add feature to download/save video in hd quality and remove buy premium popup

**Comment by cuynu** [comment]
Impossible. use an external downloader in video player instead
